version: '3'
services:
  bookstore-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
